# Generated by Django 2.2.28 on 2024-04-30 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_auth', '0012_removed_can_view_api_key_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'},
                                   help_text='Required. 254 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                   max_length=254, unique=True, validators=[
                    django.core.validators.RegexValidator('^[\\w.@+-]+$',
                                                          'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')],
                                   verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='historicalapplicationuser',
            name='username',
            field=models.CharField(db_index=True,
                                   error_messages={'unique': 'A user with that username already exists.'},
                                   help_text='Required. 254 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                   max_length=254, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$',
                                                                                                     'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')],
                                   verbose_name='username'),
        ),
    ]
